version : '3'
services:
  mysql:
    image: mysql:latest
    container_name: pre_onboarding_internship_mysql
    restart: always
    ports:
      - "3304:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      TZ: Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - 'echo "Wanted''s pre_onboarding_internship assignment starts!"'
    volumes:
      - ./data/mysql/:/var/lib/mysql

